"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Tree_1 = require("./Tree");
var Node_1 = require("./Node");
var tree = new Tree_1.Tree();
tree.insertNode(new Node_1.Node(20));
tree.insertNode(new Node_1.Node(10));
tree.insertNode(new Node_1.Node(15));
tree.insertNode(new Node_1.Node(27));
tree.insertNode(new Node_1.Node(18));
tree.insertNode(new Node_1.Node(8));
tree.insertNode(new Node_1.Node(7));
tree.insertNode(new Node_1.Node(26));
// tree.insertNode(new Node<number>(12));
// tree.insertNode(new Node<number>(11));
// tree.insertNode(new Node<number>(13));
tree.insertNode(new Node_1.Node(19));
tree.insertNode(new Node_1.Node(29));
// tree.insertNode(new Node<number>(14));
// // tree.insertNode(new Node<number>(17));
// tree.insertNode(new Node<number>(13.5));
tree.insertNode(new Node_1.Node(9));
// console.log(tree);
console.log("==============================");
tree.deleteNode(15);
console.log(tree.roof.left.right);
