"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ListPatient_1 = require("./ListPatient");
var Patient_1 = require("./Patient");
var patient1 = new Patient_1.Patient("Smith", 5);
var patient2 = new Patient_1.Patient("Jones", 4);
var patient3 = new Patient_1.Patient("Fehrenbach", 6);
var patient4 = new Patient_1.Patient("Brown", 1);
var patient5 = new Patient_1.Patient("Ingram", 1);
var listPatients1 = new ListPatient_1.ListPatient();
listPatients1.enqueue(patient1);
listPatients1.enqueue(patient2);
listPatients1.enqueue(patient3);
listPatients1.enqueue(patient4);
listPatients1.enqueue(patient5);
console.log("Danh sách bệnh nhân ban đầu:");
console.table(listPatients1.getListUnexaminedPatients());
listPatients1.sortListUnexaminedPatients();
console.log("Danh sách bệnh nhân nhập viện theo độ ưu tiên: ");
console.table(listPatients1.getListUnexaminedPatients());
console.log("===============================================");
console.log(listPatients1.examinedPatient());
console.table(listPatients1.examinedNextPatient());
console.log("===============================================");
console.log("Danh sách bệnh nhân chưa được khám: ");
console.table(listPatients1.getListUnexaminedPatients());
console.log("Danh sách bệnh nhân đã được khám: ");
console.table(listPatients1.getListExaminedPatients());
